import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDatabase1689128375959 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "Accounts" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" text,
        "account_number" text,
        "created_at" timestamptz,
        "updated_at" timestamptz,
        "deleted_at" timestamptz
      );
      
      CREATE TABLE "Wallets" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "account_id" int,
        "created_at" timestamptz,
        "updated_at" timestamptz,
        "deleted_at" timestamptz
      );
      
      CREATE TABLE "Coins" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" text,
        "created_at" timestamptz,
        "updated_at" timestamptz,
        "deleted_at" timestamptz
      );
      
      CREATE TABLE "CoinBalances" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "wallet_id" int,
        "coin_id" int,
        "balance" decimal,
        "created_at" timestamptz,
        "updated_at" timestamptz,
        "deleted_at" timestamptz
      );
      
      CREATE TABLE "Offers" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "seller_account_id" int,
        "buyer_account_id" int,
        "coin_id" int,
        "unit_price" decimal,
        "amount" decimal,
        "created_at" timestamptz,
        "updated_at" timestamptz,
        "deleted_at" timestamptz
      );
      
      ALTER TABLE "Wallets" ADD FOREIGN KEY ("account_id") REFERENCES "Accounts" ("id");
      
      ALTER TABLE "CoinBalances" ADD FOREIGN KEY ("wallet_id") REFERENCES "Wallets" ("id");
      
      ALTER TABLE "CoinBalances" ADD FOREIGN KEY ("coin_id") REFERENCES "Coins" ("id");
      
      ALTER TABLE "Offers" ADD FOREIGN KEY ("seller_account_id") REFERENCES "Accounts" ("id");
      
      ALTER TABLE "Offers" ADD FOREIGN KEY ("buyer_account_id") REFERENCES "Accounts" ("id");
      
      ALTER TABLE "Offers" ADD FOREIGN KEY ("coin_id") REFERENCES "Coins" ("id");
  `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropDatabase('crypto_offers');
  }
}
